 GET http://localhost:5078/games
###
GET http://localhost:5078/games/1

###
POST http://localhost:5078/games
Content-Type: application/json

{
  "Name":"Hockey",
  "genreId": 3,
  "price": 97.99,
  "releaseDate": "2025-01-07"
}

###
PUT http://localhost:5078/games/1
Content-Type: application/json

{
  "name": "Street Fighter II Turbo",
  "genreId": 4,
  "price": 24.99,
  "releaseDate": "1994-02-11"
}

###
DELETE  http://localhost:5078/games/3

