 GET http://localhost:5078/games
###
GET http://localhost:5078/games/1

###
POST http://localhost:5078/games
Content-Type: application/json

{
  "name": "God of War Ragnarok",
  "genre": "Action",
  "price": 69.99,
  "releaseDate": "2022-11-09"
}

