 GET http://localhost:5078/games
###
GET http://localhost:5078/games/1

###
POST http://localhost:5078/games
Content-Type: application/json

{
  "name": "God of War Ragnarok",
  "genre": "Action",
  "price": 69.99,
  "releaseDate": "2022-11-09"
}

###
PUT http://localhost:5078/games/1
Content-Type: application/json

{
  "name": "Street Fighter II Turbo",
  "genre": "Fighting",
  "price": 24.99,
  "releaseDate": "1994-02-11"
}

